### ISSUE TITLE
Home Assistant - Thermostat - No manual mode

### ISSUE THREAD

**Issue by majdzik84** [proddy/EMS-ESP#172]
I have a problem with the thermostat in the Home assistant.
- I have the option of "Auto" and "OFF", **No Manual mode** in Lovelace.
- When the auto mode is set and the temperature is changed, the day or night temperature changes but 0 degrees is shown on the thermostat. It's normal?.  [Screen](https://www.dropbox.com/s/cea9w8gg9b2ghtb/1.png?dl=0)
- When I try to call "Manual" I have an error :

`2019-08-16 10:49:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1799655120] value is not allowed for dictionary value @ data['hvac_mode']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 128, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1213, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value is not allowed for dictionary value @ data['hvac_mode']`

I have:
`EMS-ESP version 1.8.1
System stats:
Connected to wireless network ems-esp with signal strength 64%
MQTT is connected 
System uptime: 0 days 15 hours 40 minutes 41 seconds

EMS devices found:
Nefit Topline Compact/**Buderus GB162** (DeviceID:0x08 ProductID:115 Version:03.06)
**RC35** (DeviceID:0x10 ProductID:86 Version:31.07)
`

**Comment by proddy** [comment]
Hi, HA made some changes to the climate component (see https://github.com/proddy/EMS-ESP/issues/153) after 0.96 and the climate.yaml file needed modifying as different thermostats respond to different commands. Can you check your .yaml file? I'll also try and reproduce here.

**Comment by majdzik84** [comment]
Hi. I think I have the correct configuration from your climate.yaml

```
  - platform: mqtt
    name: Thermostat
    modes:
      - "auto"
      - "manual"
      - "off"

    mode_state_topic: "home/ems-esp/thermostat_data"
    current_temperature_topic: "home/ems-esp/thermostat_data"
    temperature_state_topic: "home/ems-esp/thermostat_data"

    temperature_command_topic: "home/ems-esp/thermostat_cmd_temp"
    mode_command_topic: "home/ems-esp/thermostat_cmd_mode"

    mode_state_template: "{{ value_json.thermostat_mode }}"
    current_temperature_template: "{{ value_json.thermostat_currtemp }}"
    temperature_state_template: "{{ value_json.thermostat_seltemp }}"

    temp_step: 0.5
```

https://github.com/proddy/EMS-ESP/blob/master/doc/home_assistant/climate.yaml
