### ISSUE TITLE
HA statistics - share ideas

### ISSUE THREAD

**Issue by S-Przybylski** [proddy/EMS-ESP#223]
Dear all
i am interested in statistics about my heating. I just started to learn a little bit about the historical statisics in HA (and yes i am aware that functions like max, min, mean, integrate and differentiate could easily be done with Grafana - i also use it). But i am also interested in simple functions within HA.

So my first question was, how long does the heating heats the warm water and heating circuit itself?
Please note: The yesterday value will be calculated

````
sensors.yaml:
##########################
#Heating Test historical statistics
##########################
- platform: history_stats
  name: heating_warmwater_hst_runtime_per_day
  entity_id: binary_sensor.heating_warmwater
  state: 'on'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: history_stats
  name: heating_warmwater_hst_ratio_per_day
  entity_id: binary_sensor.heating_warmwater
  state: 'on'
  type: ratio
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: history_stats
  name: heating_warmwater_hst_ratio_between_5_and_23
  entity_id: binary_sensor.heating_warmwater
  state: 'on'
  type: ratio
# between 5 -23h
  end: '{{ ((as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) | int) - 3600)  }}'
  duration:
    hours: 18

- platform: history_stats
  name: heating_heating_hst_runtime_per_day
  entity_id: binary_sensor.heating_heating
  state: 'on'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: history_stats
  name: heating_heating_hst_ratio_per_day
  entity_id: binary_sensor.heating_heating
  state: 'on'
  type: ratio
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24
````

and the template sensors to identify if the heating works in heating mode or warm water mode:
````
binary_sensors.yaml:
##########################
# for Heating Test historical statistics
##########################
- platform: template
  sensors:
    heating_warmwater:
      friendly_name: "Heating Warmwater"
      value_template: >-
       {% if is_state("binary_sensor.heating", "on") and is_state("sensor.Warm_Water_3_way_valve", "on") and is_state("sensor.boiler_pump", "on") %} {{ true }}
       {% else %} {{ false }}
       {% endif %}
# used to get frequent updates!!!
      entity_id:
        - binary_sensor.heating
        - sensor.Warm_Water_3_way_valve
        - sensor.current_flow_temperature

- platform: template
  sensors:
    heating_heating:
      friendly_name: "Heating circuit"
      value_template: >-
       {% if is_state("binary_sensor.heating", "on") and is_state("sensor.Warm_Water_3_way_valve", "off") and is_state("sensor.boiler_pump", "on") %} {{ true }}
       {% else %} {{ false }}
       {% endif %}
# used to get frequent updates!!!
      entity_id:
        - binary_sensor.heating
        - sensor.Warm_Water_3_way_valve
        - sensor.current_flow_temperature
````
What do you think about that?

Do you have other interessing ideas?

**Comment by proddy** [comment]
I've added this to the wiki

**Comment by majdzik84** [comment]
Activating one-time hot water charging
DHW once (OneTimeWater) 

switch.yaml
```
      one_time_water:
        friendly_name: OneTimeWater
        value_template: "{{ is_state('sensor.one_time_water', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.one_time_water_on
        turn_off:
          service: script.turn_on
          entity_id: script.one_time_water_off
```

scripts.yaml
```

  one_time_water_on:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'home/ems-esp/boiler_cmd_wwonetime'
          payload: '1'
          
  one_time_water_off:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'home/ems-esp/boiler_cmd_wwonetime'
          payload: '0'
```

sensors.yaml
```
  - platform: mqtt
    state_topic: 'home/ems-esp/boiler_data'
    name: 'one_time_water'
    value_template: '{{ value_json.wWOnetime }}'
```

**Comment by proddy** [comment]
thanks @majdzik84 . added to https://github.com/proddy/EMS-ESP/wiki/Home-Assistant

**Comment by S-Przybylski** [comment]
I tried to calculate the energy consumption of the heating as a first try.

To use the reset function, please activate python scripting and create a file located at ./python_scripts/set_state.py (content see below)

sensors.yaml:
````
#####################################################################################
# Version 0.1
# GB172-20 (2014)
# Calculate current boiler power and try to estimate gas consumption
# GB172-20 Vendor says: 25% = 5,2kW, 100% = 20,6kW and 123% 23,8kW
# Factor to adapt values: my boiler seems to have 1.635% more power then calculated
#####################################################################################
- platform: template
  sensors:
    heating_power_boiler:
      friendly_name: "Boiler current heating power"
      unit_of_measurement: 'W'
      value_template: >-
        {%- set current_power = states('sensor.burner_current_power')| int -%}
        {%- if is_state("binary_sensor.heating", "on") -%}
           {%- if current_power == 0 -%}
             0
           {%- elif current_power <= 25 -%}
             {{ ((((current_power * 208) | float) * 1.01635) | round(0)) | int }}
           {%- elif current_power <= 100 -%}
             {{ ((((((current_power - 25) | float) * 205) + 5200) * 1.01635) | round(0)) | int }}
           {%- elif current_power > 100 -%}
             {{ ((((((current_power - 100)| float) * 139.13) + 20600) * 1.01635) | round(0)) | int }}
           {%- endif -%}
        {%- else -%}
          0
        {%- endif -%}
      entity_id:
        - binary_sensor.heating
        - sensor.burner_current_power
        - sensor.boiler_pump
        - sensor.Warm_Water_3_way_valve
        - sensor.current_flow_temperature

#####################################################################################
# optional:

# Heating power warmwater
- platform: template
  sensors:
    heating_power_ww:
      friendly_name: "current heating power warmwater"
      unit_of_measurement: 'W'
      value_template: >-
        {% if is_state("sensor.Warm_Water_3_way_valve", "on") and is_state("binary_sensor.heating", "on") %} {{ states.sensor.heating_power_boiler.state }}
        {%- else -%}
        0
        {%- endif -%}
      entity_id:
        - sensor.heating_power_boiler
        - binary_sensor.heating
        - sensor.burner_current_power
        - sensor.Warm_Water_3_way_valve
        - sensor.current_flow_temperature

- platform: template
  sensors:
    heating_power_hc:
      friendly_name: "current heating power heat circuit"
      unit_of_measurement: 'W'
      value_template: >-
        {% if is_state("sensor.Warm_Water_3_way_valve", "off") and is_state("binary_sensor.heating", "on") %} {{ states.sensor.heating_power_boiler.state }}
        {%- else -%}
        0
        {%- endif -%}
      entity_id:
        - sensor.heating_power_boiler
        - binary_sensor.heating
        - sensor.burner_current_power
        - sensor.Warm_Water_3_way_valve
        - sensor.current_flow_temperature

#####################################################################################
# integrators to calculate engery consumption
# note: these integrators could be reset by using an external python script

- platform: integration
  source: sensor.heating_power_boiler
  name: energy_consumption_boiler
  unit_time: h
  unit_prefix: k
  method: left
  round: 3

- platform: integration
  source: sensor.heating_power_ww
  name: energy_consumption_ww
  unit_time: h
  unit_prefix: k
  method: left
  round: 3

- platform: integration
  source: sensor.heating_power_hc
  name: energy_consumption_hc
  unit_time: h
  unit_prefix: k
  method: left
  round: 3
#####################################################################################
# gas meter calculation
# mainly used to check that the calculated power consumption is valid!
# calculation:
# my last bill shows at least two factors to calculate the kWh from m³
#    key figure:        9.8719
#    location_update:   0.9617
#    resulting factor:  9.49380 kWh/m³ (key_figure * location_update)
# factor can be updated using the field input_number.gas_meter_factor

- platform: template
  sensors:
    gas_meter_total:
      friendly_name: "GAS meter (calculated)"
      unit_of_measurement: 'm³'
      value_template: >-
         {{ ((((states('sensor.energy_consumption_boiler') | float) * 1000) / (states('input_number.gas_meter_factor') | float )) + (states('input_number.gas_meter_bias') | float)) | round(3) }}
      entity_id:
        - sensor.energy_consumption_gastherme
        - input_number.gas_meter_bias
        - input_number.gas_meter_factor
############## sensors.yaml end ######################################################
````

scripts.yaml:
````
#####################################################################################
# Reset GAS meter
  reset_gas_meter:
    alias: Reset GAS meter
    sequence:
# idea: copy the current gas meter value into the bias and reset the integrators
# used a external python script - see: https://community.home-assistant.io/t/how-to-manually-set-state-value-of-sensor/43975/3
# see parts of https://github.com/gb53smith/Hass
# note: utility_meter could not be reset by this script
      - service: input_number.set_value
        data_template:
          entity_id: input_number.gas_meter_bias
          value: "{{ states('sensor.gas_meter_total') }}"
      - service: python_script.set_state
        data_template:
          entity_id: sensor.energy_consumption_boiler
          state: 0
      - service: python_script.set_state
        data_template:
          entity_id: sensor.energy_consumption_ww
          state: 0
      - service: python_script.set_state
        data_template:
          entity_id: sensor.energy_consumption_hc
          state: 0
############## scripts.yaml end ######################################################
````
groups.yaml:
````
######################################################################################
boiler_energy_stats:
  name: 'Energy statistics'
  view: no
  control: hidden
  entities:
    - sensor.heating_boiler
    - sensor.heating_ww
    - sensor.heating_hc
    - sensor.energy_consumption_boiler
    - sensor.energy_consumption_ww
    - sensor.energy_consumption_hc
    - sensor.gastherme_energy_consumption_boiler_daily
    - sensor.gastherme_energy_consumption_ww_daily
    - sensor.gastherme_energy_consumption_boiler_monthly
    - sensor.gastherme_energy_consumption_hc_daily
    - sensor.gastherme_energy_consumption_ww_monthly
    - sensor.gastherme_energy_consumption_hc_monthly
    - sensor.gas_meter_total
    - script.reset_gas_meter
    - input_number.gas_meter_bias
    - input_number.gas_meter_factor
############## groups.yaml end ######################################################
````

configuration.yaml:
````
######################################################################################
# Enable CUSTOMIZED PYTHON SCRIPTS
python_script:

######################################################################################
# input_number
# to enter the m³ to kWh factor see sensor calculation

input_number:
  gas_meter_bias:
    name: "Gas meter bias"
    min: 00001
    max: 90000
    step: 0.001
    unit_of_measurement: "m³"
    icon: mdi:fire
    mode: box
  gas_meter_factor:
    name: "Factor m³ to kWh x 1000"
    min: 8500
    max: 20000
    step: 1
    unit_of_measurement: ""
    icon: mdi:fire
    mode: box
#
######################################################################################
#
# optional
# try to calculate daily and monthly values within HA
# note: 
#      reset could only be performed when adding taiffs or by stopping HA and manually update the .storage/core.restore_state
#      historian of HA resricts long term analytics!!!
# could be better if calculated by grafana
# or add additional automation / sensor to gather each day the value of the last day attribute

utility_meter:
  gastherme_energy_consumption_boiler_daily:
    source: sensor.energy_consumption_boiler
    cycle: daily
  gastherme_energy_consumption_boiler_monthly:
    source: sensor.energy_consumption_boiler
    cycle: monthly

  gastherme_energy_consumption_ww_daily:
    source: sensor.energy_consumption_ww
    cycle: daily
  gastherme_energy_consumption_ww_monthly:
    source: sensor.energy_consumption_ww
    cycle: monthly

  gastherme_energy_consumption_hc_daily:
    source: sensor.energy_consumption_hc
    cycle: daily
  gastherme_energy_consumption_hc_monthly:
    source: sensor.energy_consumption_hc
    cycle: monthly
######################################################################################
````

set_state.py
````
#==================================================================================================
#  python_scripts/set_state.py 
# thanks rodpayne - see https://community.home-assistant.io/t/how-to-manually-set-state-value-of-sensor/43975/3
#==================================================================================================
#--------------------------------------------------------------------------------------------------
# Set the state or other attributes for the entity specified in the Automation Action
#--------------------------------------------------------------------------------------------------
inputEntity = data.get('entity_id')
if inputEntity is None:
    logger.warning("===== entity_id is required if you want to set something.")
elif hass.states.get(inputEntity) is None:
    logger.warning("===== unknown entity_id: %s", inputEntity)
else:
    inputStateObject = hass.states.get(inputEntity)
    inputState = inputStateObject.state
    inputAttributesObject = inputStateObject.attributes.copy()

    for item in data:
        newAttribute = data.get(item)
        logger.debug("===== item = {0}; value = {1}".format(item,newAttribute))
        if item == 'entity_id':
            continue            # already handled
        elif item == 'state':
            inputState = newAttribute
        else:
            inputAttributesObject[item] = newAttribute
    hass.states.set(inputEntity, inputState, inputAttributesObject)

````
