### ISSUE TITLE
Change sensor state texts in HA

### ISSUE THREAD

**Issue by glitter-ball** [proddy/EMS-ESP#281]
**Question**
How do I change the texts HA displays for sensors from EMS-ESP?

Conscious that this might be better asked on an HA forum, but it involves MQTT data from EMS-ESP, so hoping someone here can help.

I pick up the 3-way valve position from my boiler which HA shows as ON (hot water position) or OFF (heating position). I'd like to change the widget so it shows 'Heating' or 'Hot Water' instead.

The relevant bit of my sensor.yaml file looks like this:

```
- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: '3-way valve'
  icon: 'mdi:valve'
  value_template: '{{ value_json.wWHeat }}'
#  value_template: >-
#         {% if is_state('value_json.wWHeat', 'off') %}
#          HW
#        {% else %}
#          CH
#        {% endif %}

```
I tried the commented out lines in place of the original value_template line but that failed with an error. I then tried to use this example:

```
- platform: mqtt
  name: DoorSensor1
  friendly_name: My Door
  state_topic: "house/door"
  state_open: "OPENED"
  state_closed: "CLOSED"
  optimistic: false
  retain: false
  value_template: '{{ value }}'
```
So I added state_xxx definitions and that, too, barfed with an error when I checked the config file. So, any ideas on this would be appreciated, assuming that it's actually possible. Thanks.

**Comment by proddy** [comment]
Haven't tested it but your first try looks ok. Something like:

```yaml
- platform: mqtt
  state_topic: 'home/ems-esp/boiler_data'
  name: '3-way valve'
  icon: 'mdi:valve'
  value_template: "{% if value_json.wWHeat == 'off' %} HW {% else %} CH {% endif %}"
```

its yaml so watch out for indentation. Every space counts!
