### ISSUE TITLE
Gate restart when trying to change temperatures - 1.9.5b17

### ISSUE THREAD

**Issue by majdzik84** [proddy/EMS-ESP#298]
When I change the room / water temperature in HA, the gate restarts. There is no information in telnet - it simply disconnects. The temperature remains unchanged.

**Comment by proddy** [comment]
Thanks for reporting. I'll look into it. I've also heard reports of the latest 1.9.5 of not always detecting EMS devices.

**Comment by proddy** [comment]
I tested this on 1.9.5b17 and can't reproduce. Does it always happen? Does it happen if you publish MQTT commands? Or if you try the same from Telnet commands?

**Comment by majdzik84** [comment]
I don't think it happens every time. (I tested it before and it seemed that every time) I just raised the temperature and it was set correctly.

-The problem (restart) usually occurs when I set the temperature
- I also noticed restart in telnet but not so often.

After restart, the situation returned and I noticed that it does not give set temp. And current temp.

![1](https://user-images.githubusercontent.com/31352476/72388063-46d67980-3725-11ea-8ed1-d3bf2ca06d84.jpg)

sometimes I also see
![image](https://user-images.githubusercontent.com/31352476/72388405-24912b80-3726-11ea-99d2-c9c524a66f40.png)

**Comment by proddy** [comment]
@majdzik84 lets focus on the thermostat readings issue. Are you saying after a restart HC2 is shown correctly and then you get wrong values? Is it just the Mode?

**Comment by majdzik84** [comment]
At this point, I see what below:
![image](https://user-images.githubusercontent.com/31352476/72680872-0416f780-3abf-11ea-9fc7-6d66e392923d.png)

At this point, I see what below:

Note that this is night (off) mode.
How do I change the mode to e.g. DAY (heat)

![image](https://user-images.githubusercontent.com/31352476/72680957-a1722b80-3abf-11ea-8184-946d28e0f097.png)

Unfortunately, when the temperature changes, the gate restarts

**Comment by proddy** [comment]
Could you create a new issue for the HC2 mode issue, and lets leave this to the crashes.

On the crashes: I just can't reproduce so need to work with you on a test case that always fails
On the modes: I need some example telegrams for 0x47 and 0x48 (this is HC2 on RC35) to see why the data is missing.

**Comment by proddy** [comment]
@majdzik84 are you still experiencing restarts when changing temperatures via MQTT and the Telnet client?

**Comment by majdzik84** [comment]
@proddy Unfortunately, restarts still occur at every temperature change by mqtt.

Telnet did not cause any restart during 30 attempts to change temperatures and modes

**Comment by proddy** [comment]
@majdzik84 can you post the MQTT command you are sending? We need to trace where in the code its crashing

**Comment by majdzik84** [comment]
@proddy mqtt command is sent by Home assistant 0.104.3. how can i get them ??

**Comment by proddy** [comment]
try and reproduce with Telnet. Then I know if the bug is in the core code or the mqtt code. Open a telnet and do something like `thermostat temp 22`  or `thermostat temp 2 22` for HC2. We're just trying to make it crash

**Comment by majdzik84** [comment]
Change in telenet did not cause restart (10 changes - 0 restarts)
A change in HA always causes a restart. (10 changes - 10 restarts)

**Comment by proddy** [comment]
can you use something like MQTT explorer to capture the MQTT that is being sent from HA?

**Comment by majdzik84** [comment]
I don't know where I can get the specific mqtt command. Will this screen help? I just changed the HC2 temperature to 21.5C

![image](https://user-images.githubusercontent.com/31352476/73593791-2457a500-4508-11ea-8775-9edc023684d1.png)

**Comment by MichaelDvP** [comment]
use **thermostat_cmd_temp2 21.5** to change the temperature, only insert the temperature in °C 
I don't know why mqtt-explorer does not show the other cmd-subscriptions, but also writing a wrong, but valid, json to writeable commands like thermostat_cmd affects a restart. 
**thermostat_cmd {"cmd":"temp2","data":21}** 
works as expected.
**thermostat_cmd {"hc2":{"temp": 21}}**
or something else restarts the ems-esp.
double-check the wiki to send valid commands.

**Comment by proddy** [comment]
thanks @MichaelDvP for pointing out the error (again). I'm fixing it now

**Comment by proddy** [comment]
fixed. @majdzik84 you shouldn't see any crashes anymore. But I think the problem is your Home Assistant configuration as it looks like you're sending the wrong topics. See https://emsesp.github.io/docs/#/Home-Assistant

**Comment by majdzik84** [comment]
@proddy   unfortunately the patch doesn't work for me :(
My HA configuration is exactly like in the wiki. In version 1.9.4b10, these settings worked correctly.


```
  - platform: mqtt
    name: Parter
    modes:
      - "auto"
      - "heat"
      - "off"

    mode_state_topic: "home/ems-esp/thermostat_data"
    current_temperature_topic: "home/ems-esp/thermostat_data"
    temperature_state_topic: "home/ems-esp/thermostat_data"

    temperature_command_topic: "home/ems-esp/thermostat_cmd_temp2"
    mode_command_topic: "home/ems-esp/thermostat_cmd_mode2"


    mode_state_template: "{% if value_json.hc2.mode == 'manual' %} heat {% else %} {{value_json.hc2.mode}} {% endif %}"
    current_temperature_template: "{{ value_json.hc2.currtemp }}"
    temperature_state_template: "{{ value_json.hc2.seltemp }}"

    temp_step: 0.5

```
