### ISSUE TITLE
MQTT home assistant not connecting

### ISSUE THREAD

**Issue by sand3rk** [proddy/EMS-ESP#350]
**Question**
*A clear and concise description of what the problem/doubt is.*
I set mqtt setting is ems-esp webui. ems-esp says connected to mqtt. Does not popup in HA/intergrations/MQTT.

Also added 
```
climate:
  - platform: mqtt
    name: Thermostat
    modes:
      - "auto"
      - "heat"
      - "off"
    
    mode_command_topic: "home/ems-esp/thermostat_cmd_mode1"
    temperature_command_topic: "home/ems-esp/thermostat_cmd_temp1"
   
    mode_state_topic: "home/ems-esp/thermostat_data"
    current_temperature_topic: "home/ems-esp/thermostat_data"
    temperature_state_topic: "home/ems-esp/thermostat_data"
  
    mode_state_template: "{% if value_json.hc1.mode in ['manual', 'day'] %} heat {% elif value_json.hc1.mode in ['night', 'off'] %} off {% else %} auto {% endif %}"

    current_temperature_template: "{{ value_json.hc1.currtemp }}"
    temperature_state_template: "{{ value_json.hc1.seltemp }}"
   
    temp_step: 0.5
  
  - platform: mqtt
    name: Boiler
    modes:
      - "auto"
      - "off"
    min_temp: 40
    max_temp: 60
    temp_step: 1
  
    current_temperature_topic: "home/ems-esp/boiler_data"
    temperature_state_topic: "home/ems-esp/boiler_data"
    mode_state_topic: "home/ems-esp/boiler_data"

    current_temperature_template: "{{ value_json.wWCurTmp }}"
    temperature_state_template: "{{ value_json.wWSelTemp }}"
    mode_state_template: "{% if value_json.wWActivated == 'off' %} off {% else %} auto {% endif %}"

    temperature_command_topic: "home/ems-esp/boiler_cmd_wwtemp"
    mode_command_topic: "home/ems-esp/boiler_cmd_wwactivated"
```
  
But thermostat card stays grey.

![mqtt1](https://user-images.githubusercontent.com/31222573/76865818-8de70500-6863-11ea-995a-ae5586524d51.png)
![mqtt4](https://user-images.githubusercontent.com/31222573/76866081-e8806100-6863-11ea-991c-a9ef707b4ed9.png)
![mqtt3](https://user-images.githubusercontent.com/31222573/76866087-e918f780-6863-11ea-94af-fd0dcc1b5f95.png)
![mqtt2](https://user-images.githubusercontent.com/31222573/76866090-e9b18e00-6863-11ea-8ea5-4d472d7f411c.png)
![mqtt5](https://user-images.githubusercontent.com/31222573/76866092-ea4a2480-6863-11ea-8b96-dcc96f23e026.png)

**Device information**
ems-esp: version 1.9.4
mqtt broker: 5.1 (lastest)
