### ISSUE TITLE
Climate error in HA - config issue or missing data at start-up?

### ISSUE THREAD

**Issue by glitter-ball** [proddy/EMS-ESP#517]
**Question**
I've been getting a persistent error in the HA log:

`2020-09-21 21:14:50 ERROR (MainThread) [homeassistant.components.mqtt.climate] Could not parse temperature from `
![image](https://user-images.githubusercontent.com/57917148/94177389-5a7bd780-fe91-11ea-8cd1-32058a5e6777.png)

That's all I get - rest is truncated, sadly. It seems to produce a burst (16 this time) and then stop. I've had a look in my climate.yaml file and am struggling to see what the issue is, if there is one. Alternatively, is this an issue with HA looking for data which hasn't come in over MQTT yet? When I start MQTT Explorer I can wait a while for thermostat data - e.g. just checked and first thermostat telegram came in 34 seconds after the first boiler one.

HA tiles look OK...
![image](https://user-images.githubusercontent.com/57917148/94178012-6916be80-fe92-11ea-8932-a1ea98576be5.png)

**Device information**
```
/config/climate.yaml

- platform: mqtt
  name: Heating
  modes:
    - "auto"
    - "heat"
    - "off"
  mode_command_topic: "ems-esp/thermostat_cmd_mode1"
  temperature_command_topic: "ems-esp/thermostat_cmd_temp1"
   
  mode_state_topic: "ems-esp/thermostat_data1"
  current_temperature_topic: "ems-esp/thermostat_data1"
  temperature_state_topic: "ems-esp/thermostat_data1"

  mode_state_template: "{{ value_json.mode }}"
  current_temperature_template: "{{ value_json.currtemp }}"
  temperature_state_template: "{{ value_json.seltemp }}"
   
  temp_step: 0.5
  
- platform: mqtt
  name: Hot Water
  modes:
    - "auto"
    - "off"
  min_temp: 40
  max_temp: 60
  temp_step: 1
  
  current_temperature_topic: "ems-esp/boiler_data"
  temperature_state_topic: "ems-esp/boiler_data"
  mode_state_topic: "ems-esp/boiler_data"

  current_temperature_template: "{{ value_json.wWCurTmp }}"
  temperature_state_template: "{{ value_json.wWSelTemp }}"
  mode_state_template: "{% if value_json.wWActivated == 'off' %} off {% else %} auto {% endif %}"

  temperature_command_topic: "ems-esp/boiler_cmd_wwtemp"
  mode_command_topic: "ems-esp/boiler_cmd_wwactivated"
  

```
