### ISSUE TITLE
Create a derived sensor value in HA

### ISSUE THREAD

**Issue by glitter-ball** [proddy/EMS-ESP#519]
**Question**
Apologies - this is a bit off-topic, more a HA question than an EMS-ESP one. But it might be useful to other people too.

How can I create a new sensor value in HA from two existing values? Specifically, if I want to create a new value...

`differential = flow_temp - return_temp`

... how would I code that in the sensor.yaml file? Existing entries are:

```
- platform: mqtt
  state_topic: 'ems-esp/sensor_28-BE2A-7791-0402-65'
  name: 'Return temp'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temp | round(1) }}'

- platform: mqtt
  state_topic: 'ems-esp/boiler_data'
  name: 'Flow temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.curFlowTemp }}'

```

Thanks!

**Comment by proddy** [comment]
from the top of my head you would do something like

```yaml
- platform: template
  sensors:
    differential:
      value_template: "{{ (states('sensor.flow_temperature') | float) - (states('sensor.return_temp') | float) }}"
```

You can try the formula directly in HA by going to the Developer Tools->Template and copying in the {{ ... }} bit

**Comment by glitter-ball** [comment]
Thanks - this seems to work in the Developer Tools preview. I want to round to one decimal place, so tried inserting a `round(1)` filter in several places  (with extra brackets as necessary) to achieve this but without luck. Any idea how to crack, that?

**Comment by glitter-ball** [comment]
The issue is something to do with the subtraction operator. If I just put each reading with the `float() `filter into the template, they both report back values in the form `xx.x`. This was a bit of a suprise as the return_temp has a `round(1)` in it because the Dallas sensor values aren't necessarily neat numbers. Anyway, on their own they're OK.

Putting the subtraction operator in produces ridiculous numbers of decimal places. Adding and multiplying also. Maybe I'm missing something with floating point maths?

**Comment by glitter-ball** [comment]
Great - cracked it! Thanks for your help.

![image](https://user-images.githubusercontent.com/57917148/94344718-22070580-0019-11eb-9895-4a8b7da3f007.png)

**Comment by proddy** [comment]
Fancy pants!

**Comment by glitter-ball** [comment]
Ha! Yep - more ‘saddo numbers‘ to look at and for the rest of the family to take the p*ss out of!

But... my son is learning Python now at school and getting bored with drawing houses with the turtle, so he might have to play cool and learn some HA stuff too. *8()

**Comment by glitter-ball** [comment]
For the curious, this is the complete config.yaml block:

```
- platform: template
  sensors:
    differential:
      friendly_name: "Flow-Ret diff"
      unit_of_measurement: '°C'
      icon_template: 'mdi:format-align-middle'
      value_template: "{{ (states('sensor.flow_temperature') | float - states('sensor.return_temp') | float) | round(1) }}"
```
