### ISSUE TITLE
(v2) Question - HA example config for climate, mqtt?

### ISSUE THREAD

**Issue by giovanne123** [proddy/EMS-ESP#573]
Question regarding the usage of the HA climate / thermostat within EMS-ESP v2.1/v2.1.0b10

![image](https://user-images.githubusercontent.com/16689453/97008812-97e08d00-1543-11eb-80d9-9b0ff7656980.png)

How to send changes for mode and temp within climate/mqtt?
How does a config look like for, e.g. "mode_command_topic"?
Maybe I miss something because I haven't send commands before to the EMS-ESP.
I am not using HA discover!

climate.yaml:
```
- platform: mqtt
  name: Heating Circuit 1 (HC1)
  modes:
    - "auto"
    - "heat"
    - "off"

  mode_command_topic: "ems-esp/thermostat"
  temperature_command_topic: "ems-esp/thermostat"

  mode_state_topic: "ems-esp/thermostat_data1"
  current_temperature_topic: "ems-esp/sensor_10-7E42-7001-0xxx-xx"
  temperature_state_topic: "ems-esp/thermostat_data1"

  mode_state_template: "{% if value_json.mode in ['manual', 'day'] %} heat {% elif value_json.mode in ['night', 'off'] %} off {% else %} auto {% endif %}"

  current_temperature_template: "{{ value_json.temp }}"
  temperature_state_template: "{{ value_json.seltemp }}"

  temp_step: 0.5
```

With this **mode_command_topic: "ems-esp/thermostat"** I publish mqtt with e.g.:
_topic: ems-esp/thermostat
data/payload: heat_

Do I need to generate also automations in automations.yaml or how **to get not only "heat" but {"cmd":"mode", "data": "day", "id": 1 }** into the data/payload to send?

Does someone maybe have an example config for HA?

(
As workaround I already tested this successful with and input.select and automation: 
topic: ems-esp/thermostat
payload {"cmd":"mode", "data": "{{states("input_select.thermostat_mode_hc1")}}", "id": 1 }
)
