### ISSUE TITLE
No warmwater temp selection

### ISSUE THREAD

**Issue by og9gjz567** [proddy/EMS-ESP#602]
Hi,
I've updated from the latest 1.9.x Version to the very nice looking  v2.1.1b1 ;)
I like the new UI and the mqtt autodiscover function. At the moment there is no warmwater entity:
![grafik](https://user-images.githubusercontent.com/58255842/98913423-a5948d00-24c7-11eb-8f12-87907ebd03a8.png)

Is there a easy way to get this back by yaml-code? This is my old code, but it doesn't work:

```
- platform: mqtt
  name: Warmwasser
  modes:
    - "auto"
    - "off"
  min_temp: 40
  max_temp: 60
  temp_step: 1
  
  current_temperature_topic: "ems-esp/boiler_data"
  temperature_state_topic: "ems-esp/boiler_data"
  mode_state_topic: "ems-esp/boiler_data"

  current_temperature_template: "{{ value_json.wWCurTmp }}"
  temperature_state_template: "{{ value_json.wWSelTemp }}"
  mode_state_template: "{% if value_json.wWActivated == 'off' %} off {% else %} auto {% endif %}"

  temperature_command_topic: "ems-esp/boiler_cmd"
  mode_command_topic: "ems-esp/boiler_cmd"
```

**Comment by proddy** [comment]
It should be there. If you use MQTTExplorer you should see an topic `homeassistant/sensor/ems-esp/boiler_wWCurTemp`. Can you check that?

The `Mixer hc2 Current pump status` is strange. It shouldn't be showing as an MQTT Device. It's a bug we need to fix.

**Comment by og9gjz567** [comment]
Hi,

thanks a lot. MQTT Explorer shows the topic:
![grafik](https://user-images.githubusercontent.com/58255842/98923699-4a1ccc00-24d4-11eb-9d13-7b9c0b6c7ac1.png)

**Comment by og9gjz567** [comment]
Hi,
with the following yaml code it's working for now:

```
- platform: mqtt
  name: Warmwasser
  modes:
    - "auto"
    - "off"
  min_temp: 40
  max_temp: 60
  temp_step: 1
  
  current_temperature_topic: "ems-esp/boiler_data_ww"
  temperature_state_topic: "ems-esp/boiler_data_ww"
  mode_state_topic: "ems-esp/boiler_data_ww"

  current_temperature_template: "{{ value_json.wWCurTemp }}"
  temperature_state_template: "{{ value_json.wWSelTemp }}"
  mode_state_template: "{% if value_json.wWActivated == 'off' %} off {% else %} auto {% endif %}"

  temperature_command_topic: "ems-esp/boiler"
  mode_command_topic: "ems-esp/boiler"
```
