### ISSUE TITLE
Commands refresh and publish

### ISSUE THREAD

**Issue by deejaybeam** [proddy/EMS-ESP#608]
I'm using v1.9.5 and like this project very much! - awesome!
Now I want to upgrade the existing version from 1.9.5 to 2.1 with pure mqtt integration to v2.1
One thing I'm missing is the commands to update/publish mqtt messages.
For now I use a homeassistant script to change e.g. thermostat_cmd_mode2 to auto like this:
```
'ems_hc2_auto':
  alias: HC2 auto
  sequence:
    - service: mqtt.publish
      data:
        topic: 'ems-esp/thermostat_cmd_mode2'
        payload: 'auto'
    - service: mqtt.publish
      data:
        topic: 'ems-esp/generic_cmd'
        payload: '{cmd:"refresh"}'
    - service: mqtt.publish
      data:
        topic: 'ems-esp/generic_cmd'
        payload: '{cmd:"publish"}'
```
...instantly after pushing the button in the gui.
in the documentation I don't find anything about that for the new (2.1) version.
I prefer to have messages about stats with fixed intervals so I force an update after change.

Is this possible with v2.x also?

My integration looks like this:
![image](https://user-images.githubusercontent.com/10434729/99124218-06c07b80-2602-11eb-8cc0-8186e729b4f3.png)

because of WAF (WomanAcceptanceFactor) it looks like the manual remote control...
Now - If you push a button you see an instant change.

thanks for building this awesome project!! - chris
